In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [140]:
path = 'resultados'

In [141]:
padrao_arquivos = os.path.join(path, '*.txt')  # define o padr√£o para listar todos os arquivos na pasta
lista_arquivos = glob.glob(padrao_arquivos)
lista_arquivos

['resultados\\FPGAin.txt',
 'resultados\\FPGAout-PC.txt',
 'resultados\\FPGAout_InliersOutliers.txt',
 'resultados\\FPGAout_otimizacao_memoria.txt',
 'resultados\\FPGAout_sem_otimizacao.txt']

In [131]:
def FPGAout_read(filename):
    data = []
    columns = ['step', 'model', 'bestfit', 'inliers', 'angle', 'distance']

    with open(filename, 'r') as file:
        while True:
            result = {}
            test_case = file.readline().strip()
            if not test_case:
                break
            result['step'] = int(test_case)
            result['model'] = list(map(float, file.readline()[1:-2].split(',')))
            result['bestfit'] = float(file.readline().strip())
            result['inliers'] = int(file.readline().strip())
            result['angle'] = float(file.readline().strip())
            result['distance'] = float(file.readline().strip())
            file.readline()
            data.append(result)

    return pd.DataFrame(data, columns=columns)

In [132]:
FPGA_out_PC = FPGAout_read(lista_arquivos[1])
FPGA_out_NIOS = FPGAout_read(lista_arquivos[3])
FPGA_out_NIOS_H = FPGAout_read(lista_arquivos[2])

In [133]:
modelo_df1 = pd.DataFrame(FPGA_out_PC['model'].tolist(), columns=['python_angular', 'python_linear'])
modelo_df2 = pd.DataFrame(FPGA_out_NIOS['model'].tolist(), columns=['nios_angular', 'nios_linear'])

# Concatenar as colunas "modelo" dos dois DataFrames em um novo DataFrame
modelo_concat = pd.concat([modelo_df1, modelo_df2], axis=1)

modelo_concat['erro_angular'] = abs(modelo_concat['python_angular'] - modelo_concat['nios_angular'])
modelo_concat['erro_linear'] = abs(modelo_concat['python_linear'] - modelo_concat['nios_linear'])

In [134]:
modelo_concat.round(4)

,python_angular,python_linear,nios_angular,nios_linear,erro_angular,erro_linear
0,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
1,1.8496,-9.0723,1.9253,-11.3491,0.0757,2.2768
2,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
3,0.4267,15.8526,0.4811,12.9844,0.0544,2.8682
4,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
5,0.0000,25.0000,0.0417,29.5275,0.0417,4.5275
6,-0.7649,34.2722,-0.7704,33.5928,0.0054,0.6793
7,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
8,1.1687,24.2893,1.2031,23.7109,0.0344,0.5785
9,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
10,1.1899,-10.9187,0.9908,-2.5160,0.1991,8.4028
11,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
12,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
13,0.0311,32.2548,0.0262,30.9542,0.0049,1.3006

In [135]:
modelo_df1 = pd.DataFrame(FPGA_out_PC['model'].tolist(), columns=['python_angular', 'python_linear'])
modelo_df2 = pd.DataFrame(FPGA_out_NIOS_H['model'].tolist(), columns=['nios_hardware_angular', 'nios_hardware_linear'])

# Concatenar as colunas "modelo" dos dois DataFrames em um novo DataFrame
modelo_concat_2 = pd.concat([modelo_df1, modelo_df2], axis=1)

modelo_concat_2['erro_angular'] = abs(modelo_concat_2['python_angular'] - modelo_concat_2['nios_hardware_angular'])
modelo_concat_2['erro_linear'] = abs(modelo_concat_2['python_linear'] - modelo_concat_2['nios_hardware_linear'])

In [136]:
modelo_concat_2.round(4)

,python_angular,python_linear,nios_hardware_angular,nios_hardware_linear,erro_angular,erro_linear
0,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
1,1.8496,-9.0723,1.9253,-11.3491,0.0757,2.2768
2,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
3,0.4267,15.8526,0.4811,12.9844,0.0544,2.8682
4,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
5,0.0000,25.0000,0.0417,29.5275,0.0417,4.5275
6,-0.7649,34.2722,-0.7704,33.5928,0.0054,0.6793
7,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
8,1.1687,24.2893,1.2031,23.7109,0.0344,0.5785
9,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
10,1.1899,-10.9187,0.9908,-2.5160,0.1991,8.4028
11,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
12,0.0000,25.0000,0.0000,25.0000,0.0000,0.0000
13,0.0311,32.2548,0.0262,30.9542,0.0049,1.3006

In [137]:
df = pd.DataFrame(columns=['angle_python', 'angle_nios', 'distance_python', 'distance_nios', 'erro_angle', 'erro_distance'])
df['angle_python'] = FPGA_out_PC['angle']
df['angle_nios'] = FPGA_out_NIOS['angle']
df['distance_python'] = FPGA_out_PC['distance']
df['distance_nios'] = FPGA_out_NIOS['distance']

df['erro_angle'] = abs(df['angle_python'] - df['angle_nios'])
df['erro_distance'] = abs(df['distance_python'] - df['distance_nios'])

In [138]:
df

,angle_python,angle_nios,distance_python,distance_nios,erro_angle,erro_distance
0,0.000000,0.000000,50.000000,50.000000,0.000000,0.000000
1,-1.075157,-1.091750,18.421322,18.141445,0.016593,0.279877
2,-1.075157,0.000000,50.000000,50.000000,1.075157,0.000000
3,-1.478479,-0.448391,21.436781,24.021948,1.030088,2.585167
4,-1.478479,0.000000,50.000000,50.000000,1.478479,0.000000
5,-1.478479,0.000000,50.000000,50.000000,1.478479,0.000000
6,-0.825496,0.656411,12.121742,11.000188,1.481907,1.121554
7,-0.825496,0.000000,50.000000,50.000000,0.825496,0.000000
8,-1.688544,-0.877336,0.608056,1.416667,0.811208,0.808611
9,-1.688544,0.000000,50.000000,50.000000,1.688544,0.000000
10,-2.560444,-0.780775,30.186188,27.022642,1.779669,3.163546
11,-2.560444,0.000000,50.000000,50.000000,2.560444,0.000000
12,-2.560444,0.000000,50.000000,50.000000,2.560444,0.000000
13,-2.591561,0.000000,50.000000,50.000000,2.591561,0.000000